export const SET_BACKEND_SUPPORT_ROOM = "SET_BACKEND_SUPPORT_ROOM";
export const SET_FRONTEND_SUPPORT_ROOM = "SET_FRONTEND_SUPPORT_ROOM";
export const SET_QA_SUPPORT_ROOM = "SET_QA_SUPPORT_ROOM";

export const SET_REMOVE_BACKEND_SUPPORT_ROOM =
	"SET_REMOVE_BACKEND_SUPPORT_ROOM";
export const SET_REMOVE_FRONTEND_SUPPORT_ROOM =
	"SET_REMOVE_FRONTEND_SUPPORT_ROOM";
export const SET_REMOVE_QA_SUPPORT_ROOM = "SET_REMOVE_QA_SUPPORT_ROOM";

export const WEBSOCKET_OPENED = "WEBSOCKET_OPENED";

export const SET_LOADING_DATA = "SET_LOADING_DATA";
