export const SET_BACKEND_SUPPORT_ROOM = "SET_BACKEND_SUPPORT_ROOM";
export const SET_FRONTEND_SUPPORT_ROOM = "SET_FRONTEND_SUPPORT_ROOM";
export const SET_QA_SUPPORT_ROOM = "SET_QA_SUPPORT_ROOM";

export const INCREASE_COUNT = "INCREASE_COUNT";
